---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: eventlisteners.triggers.tekton.dev
  labels:
    app.kubernetes.io/component: tekton
    app.kubernetes.io/name: eventlisteners
    app.kubernetes.io/part-of: tekton-triggers
spec:
  group: triggers.tekton.dev
  names:
    kind: EventListener
    plural: eventlisteners
    singular: eventlistener
    shortNames:
      - el
    categories:
      - tekton
      - tekton-triggers
  preserveUnknownFields: false
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    subresources:
      status: {}
    additionalPrinterColumns:
      - name: Address
        type: string
        jsonPath: .status.address.url
      - name: Available
        type: string
        jsonPath: ".status.conditions[?(@.type=='Available')].status"
      - name: Reason
        type: string
        jsonPath: ".status.conditions[?(@.type=='Available')].reason"
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
...
